spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/molorane/snooker-config.git #tells spring where to locate the config files
          cloneOnStart: true
          password: Blessing**88NMM
          username: molorane.mothusi@gmail.com
  security:
    user:
      password: 1234 #the password which apps will use to access its configurations
  application:
    name: snooker-config-service

server:
  port: 7777 #the port where the config-server will be accessible
